pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                // 
                bat "mvn clean -f SeleniumNewFeature/Sample"
                
            }
        }
        stage('Test') { 
            steps {
                // 
                bat "mvn test -f SeleniumNewFeature/Sample"
            }
        }
        stage('Deploy') { 
            steps {
                // 
                bat "mvn package -f SeleniumNewFeature/Sample"
            }
        }
    }
}