pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                // 
                bat "cd SeleniumNewFeature\Sample"
                bat "mvn clean"
                
            }
        }
        stage('Test') { 
            steps {
                // 
                bat "cd SeleniumNewFeature\Sample"
                bat "mvn test"
            }
        }
        stage('Deploy') { 
            steps {
                // 
                bat "cd SeleniumNewFeature\Sample"
                bat "mvn package"
            }
        }
    }
}